###############################################################################
## PostgreSQL Docker container
##
## Usage: docker-compose run -d --name postgres postgres
##
## Author: Bob Brady
##
###############################################################################
version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    container_name: postgres

volumes:
  pgdata:
    driver: local
